apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.application }}
  ports:
    - name: mqtt
      port: 1883
    - name: ws
      port: 8083